### ISSUE TITLE
Blackmagic Hyperdeck REC Feedback

### ISSUE THREAD

**Issue by Massisound** [bitfocus/companion-module-hyperdeck#7] opened 2019-05-15 14:22 UTC
**Describe the feature**
Is it possible to have a feedback from hyperdeck? Would be nice to have the chance to change button color while recording!

**Usecases**
Well if you have your hyperdeck in another room or anyway you can't turn to watch the red rec button, would be great to be able to check the recording status

**Comment by krocheck** [comment] 2019-08-23 21:43
Duplicate of #3

**Closed by krocheck** 2019-08-23 21:43 UTC
