### ISSUE TITLE
Add feedback change color Blackmagic hyperdeck

### ISSUE THREAD

**Issue by studiovideo54** [bitfocus/companion-module-hyperdeck#2] opened 2018-12-10 14:17 UTC
**Describe the feature**
Change colors buttons when press rec, play, stop ecc

**Is this platform dependent (windows, mac, ..)?**
mac

**If documentation is required to implement, do you know where to find it?**
Blackmagic hyperdeck 

**Usecases**
start stop rec hyperdeck from stream deck
![img_9249](https://user-images.githubusercontent.com/45082536/49738317-5caa7d00-fc8f-11e8-82fd-cfa82f91da3b.jpg)

**Comment by krocheck** [comment] 2019-08-23 21:44
Duplicate of #3

**Closed by krocheck** 2019-08-23 21:44 UTC
